### ISSUE TITLE
zk接口自动对接调测

### ISSUE THREAD

**Issue by felix678** [630173235/jtbox#18]

**Comment by 630173235** [comment]
依赖：
     认证服务oauth接口，需要与微信入网流程相关；
     
     @wm868  明确入网判断的条件。

**Comment by felix678** [comment]
<--- 200 Always in UTF8 mode.
---> USER xianjiet
<--- 331 Please specify the password.
---> PASS ftpuser4006780878pa4word
<--- 230 Login successful.
---> PWD
<--- 257 "/"
---> PBSZ 0
<--- 200 PBSZ set to 0.
---> PROT P
<--- 200 PROT now Private.
---> TYPE I
<--- 200 Switching to Binary mode.
---> PASV
<--- 227 Entering Passive Mode (220,112,202,227,250,43).
---- Connecting data socket to (220.112.202.227) port 64043
---- Data connection established
---> ALLO 1424
**<--- 550 Permission denied.**
---> STOR 123-333737828-610000-610000-1498171050-00002.zip
---> ABOR
---- Closing aborted data socket
put: /alidata/openwrt/ETL/data-integration/jtbox/DATA/day/123-333737828-610000-610000-1498171050-00002.zip: Access failed: 550 Permission denied. (123-333737828-610000-610000-1498171050-00002.zip)
---- Closing control socket
等待zk核查服务端，发送端每日全量脚本检查完毕。

**Comment by felix678** [comment]
程序已经调测OK

**Comment by felix678** [comment]
已经完成与zk的后台对接，数据在新老平台都正常
