### ISSUE TITLE
管理后台融合权限模块

### ISSUE THREAD

**Issue by wm868** [630173235/jtbox#21]
1.jtbox项目后台rest接口开发
2.融合权限实体的rest生成    (由于不支持jh文件上传，请修改txt为jh后执行生成）  
[tyqx_0621.txt](https://github.com/630173235/jtbox/files/1092037/tyqx_0621.txt)
3.融合业务权限管理，包括（用户登录、token生成与验证、菜单动态分配、权限及组织权限控制改造）
4.改造jtboxfront项目前台展示，调用后台权限，按权限呈现模块。
5.验证：前后台验证（涉及后台jtbox  和 页面jtboxfront）集成测试

**Comment by wm868** [comment]
@

**Comment by 630173235** [comment]
23号中午，明确是否在28号release

**Comment by 630173235** [comment]
duplicate with #9

**Comment by wm868** [comment]
已经完成权限restapi迁移实体：
JtBaseOrganization*Res
JtBaseStafforganize*Res
JtBaseRoles*Res
JtBaseRoleright*Res
JtBaseUserrole*Res
JtBaseUsergroup*Res
JtBaseUsergroupright*Res
JtBaseUserinfousergroup*Res
JtBaseOASetup*Res
JtBaseUserright*Res

未开始的权限restapi迁移实体：
JtBaseSysmenu*Res
JtBaseButton*Res
JtBaseUserinfo*Res
JtBaseSysloginlog*Res
JtBaseAppendproperty*Res
JtBaseAppendpropertyinstance*Res

**Comment by wm868** [comment]
20170624进度
1.jtbox项目后台rest接口开发（上列实体restapi改造完成）
2.融合权限实体的rest生成 (由于不支持jh文件上传，请修改txt为jh后执行生成）
tyqx_0621.txt
3.融合业务权限管理，包括（用户登录、token生成与验证、菜单动态分配、权限及组织权限控制改造）---功能改造完成，样式需要重新规划
4.改造jtboxfront项目前台展示，调用后台权限，按权限呈现模块。
5.验证：前后台验证（涉及后台jtbox 和 页面jtboxfront）集成测试

**Comment by wm868** [comment]
Leave a comment
