### ISSUE TITLE
通用权限配置的迁移

### ISSUE THREAD

**Issue by 630173235** [630173235/jtbox#9]
将备品备件的通用权限模块迁移到box项目中；
     1. 界面迁移；
     2. 接口迁移；
     3. 模型迁移；

**Comment by wm868** [comment]
.融合权限实体的rest生成    (由于不支持jh文件上传，请修改txt为jh后执行生成）  
[tyqx_0621.txt](https://github.com/630173235/jtbox/files/1092037/tyqx_0621.txt)

**Comment by wm868** [comment]
已经完成
